import { Room } from "./types";

export const ROOMS: Room[] = [
  {
    id: 1,
    name: "Skyloft Studio",
    price: "3.500.000đ",
    location: "District 1, Ho Chi Minh City",
    distance: "0.8 km",
    rating: 4.9,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCjM-qEBlh7bcsPAVADqk_Iz4JtQRWFRvhODRbV-c-GNsqGHTOuALsl9rqUOIZN_vUmeEUnOJ3kKamQESMOEU24WLyV-htyn9zCTFsel96Xh6bAX2Ozt8dIGU73EAwXraBKkIR1lO4f9SpohuEaTZJL67wBLZMS9XQH8ZPDfq0UqKPsZV0iPGSW8L6Uvc6ANouhnj0B4q5PZkqV3dtSWeqIcDBF6h-_kolSYBgvdxG_EMvbWXrkrJYZBqvQ_bVYnmywjdOrKhCmeoCu",
    verified: true,
    description: "Bright studio with a large balcony. Great natural light for your plants and morning coffee.",
    match: 75,
  },
  {
    id: 2,
    name: "Neon Loft District 3",
    price: "7.500.000đ",
    location: "District 3, Near UEH",
    distance: "800m",
    rating: 4.7,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB3VCFEpk5Rq-ljJAelkjjxZ7W1oKsXrgKtNYD--qjTb1iv5RvtRu_E8V-ZH2ovXHgnkZ4wUUS2CPA530gGImaPfruydwHU4l9aGdNNcaIfjEZnXTzks-HXEJdTkFSaIzjVf--c7MYihKM5XIMJmyf_jZYzSJ7yxjxJTtvK0zFzEEz0YNq3Pw0xxnuEi0ectn_cVIXcaNg06qbzhE0CtwPR0LCSfW7u_P-3vcuuOuoPf5hIsPCskJ6dUUGULBC3IEpyBXDG-HqIE5qb",
    verified: true,
    description: "Modern loft with neon accents. Perfect for students who love a vibrant city lifestyle.",
    match: 85,
  },
  {
    id: 3,
    name: "Modern Minimalist",
    price: "4.200.000đ",
    location: "District 7, Near RMIT",
    distance: "1.2 km",
    rating: 4.8,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDoIBWqDfsVw-jh6-STN5fizcMWY7GPZnQmgkB8UblyFHIv4qpGzMdZLR9Bl274advSLKifedSke--1RL5rxpOAFp_VNjDsI6PLDZHYUtVtmO2h_rAi2MNEYD5qrF60yiAjUXg2bnIgArNPRADvD_wXV4lNPnZctmqRc7KOO-fdxYr-wcC9UHrMSnztU4pN-JcW63lES51znBxrdALPgn0NNmRkRlE_vLtnlwxH69Rk93YFqZk2jgnI_IPK6nfMIzzyAoZacDkU392Y",
    verified: false,
    description: "Clean, minimalist design with essential amenities. Quiet neighborhood ideal for studying.",
    match: 90,
  },
  {
    id: 4,
    name: "Cozy Corner Room",
    price: "2.800.000đ",
    location: "Binh Thanh District",
    distance: "2.5 km",
    rating: 4.5,
    image: "https://picsum.photos/seed/room4/600/800",
    verified: true,
    description: "Affordable and cozy room in a friendly shared house. Close to local markets and street food.",
    match: 60,
  },
  {
    id: 5,
    name: "Riverside Apartment",
    price: "6.000.000đ",
    location: "District 2, Thao Dien",
    distance: "5.0 km",
    rating: 4.9,
    image: "https://picsum.photos/seed/room5/600/800",
    verified: true,
    description: "Spacious apartment with a stunning river view. Includes access to pool and gym.",
    match: 40,
  },
  {
    id: 6,
    name: "Vintage Studio",
    price: "3.800.000đ",
    location: "Phu Nhuan District",
    distance: "1.5 km",
    rating: 4.6,
    image: "https://picsum.photos/seed/room6/600/800",
    verified: false,
    description: "Charming studio with vintage decor. Located in a quiet alley, away from the city noise.",
    match: 80,
  },
  {
    id: 7,
    name: "Urban Oasis",
    price: "5.500.000đ",
    location: "District 10",
    distance: "3.0 km",
    rating: 4.7,
    image: "https://picsum.photos/seed/room7/600/800",
    verified: true,
    description: "A green oasis in the heart of the city. Features a shared rooftop garden.",
    match: 65,
  },
  {
    id: 8,
    name: "Student Hub Shared Room",
    price: "1.500.000đ",
    location: "District 5",
    distance: "1.0 km",
    rating: 4.2,
    image: "https://picsum.photos/seed/room8/600/800",
    verified: true,
    description: "Budget-friendly shared room. Great way to meet fellow students and make friends.",
    match: 95,
  },
  {
    id: 9,
    name: "Sunny Balcony Room",
    price: "4.000.000đ",
    location: "Tan Binh District",
    distance: "4.0 km",
    rating: 4.8,
    image: "https://picsum.photos/seed/room9/600/800",
    verified: false,
    description: "Private room with a large sunny balcony. Fully furnished and ready to move in.",
    match: 55,
  },
  {
    id: 10,
    name: "Luxury Penthouse Share",
    price: "8.500.000đ",
    location: "District 1",
    distance: "2.0 km",
    rating: 5.0,
    image: "https://picsum.photos/seed/room10/600/800",
    verified: true,
    description: "Share a luxury penthouse with young professionals. Premium amenities and breathtaking views.",
    match: 50,
  },
  {
    id: 11,
    name: "Artisan Loft",
    price: "5.200.000đ",
    location: "District 4",
    distance: "1.8 km",
    rating: 4.7,
    image: "https://picsum.photos/seed/room11/600/800",
    verified: true,
    description: "Creative loft space with high ceilings and exposed brick. Perfect for artists and designers.",
    match: 70,
  },
  {
    id: 12,
    name: "Quiet Suburb House",
    price: "3.000.000đ",
    location: "Go Vap District",
    distance: "6.0 km",
    rating: 4.4,
    image: "https://picsum.photos/seed/room12/600/800",
    verified: false,
    description: "Peaceful room in a suburban house. Ideal for those who prefer a quiet environment.",
    match: 35,
  },
  {
    id: 13,
    name: "City Center Micro-Apartment",
    price: "4.500.000đ",
    location: "District 1",
    distance: "0.5 km",
    rating: 4.6,
    image: "https://picsum.photos/seed/room13/600/800",
    verified: true,
    description: "Compact and efficient micro-apartment right in the city center. Walk to everything.",
    match: 88,
  },
  {
    id: 14,
    name: "Spacious Master Bedroom",
    price: "5.000.000đ",
    location: "District 7",
    distance: "1.5 km",
    rating: 4.9,
    image: "https://picsum.photos/seed/room14/600/800",
    verified: true,
    description: "Large master bedroom with en-suite bathroom. Located in a secure and modern building.",
    match: 82,
  },
  {
    id: 15,
    name: "Eco-Friendly Studio",
    price: "4.800.000đ",
    location: "District 2",
    distance: "4.5 km",
    rating: 4.8,
    image: "https://picsum.photos/seed/room15/600/800",
    verified: false,
    description: "Sustainable studio built with eco-friendly materials. Solar powered and energy efficient.",
    match: 45,
  },
  {
    id: 16,
    name: "Traditional Homestay",
    price: "2.500.000đ",
    location: "Binh Thanh District",
    distance: "3.5 km",
    rating: 4.3,
    image: "https://picsum.photos/seed/room16/600/800",
    verified: true,
    description: "Experience local culture in this traditional homestay. Home-cooked meals available.",
    match: 55,
  },
  {
    id: 17,
    name: "High-Rise Condo Room",
    price: "6.500.000đ",
    location: "District 4",
    distance: "2.2 km",
    rating: 4.7,
    image: "https://picsum.photos/seed/room17/600/800",
    verified: true,
    description: "Modern room in a high-rise condo. Enjoy spectacular city skyline views at night.",
    match: 68,
  },
  {
    id: 18,
    name: "Pet-Friendly Apartment",
    price: "5.500.000đ",
    location: "District 7",
    distance: "2.0 km",
    rating: 4.6,
    image: "https://picsum.photos/seed/room18/600/800",
    verified: false,
    description: "Bring your furry friends! This apartment is completely pet-friendly with a nearby park.",
    match: 72,
  }
];
